;<KHeader>
;+=========================================================================
;I               EApiDK Embedded Application Development Kit
;+=========================================================================
;I  $HeadURL$
;+=========================================================================
;I   Copyright: Copyright (c) 2002-2009, Kontron Embedded Modules GmbH
;I      Author: John Kearney,                  John.Kearney@kontron.com
;I
;I     License: All rights reserved. This program and the accompanying 
;I              materials are licensed and made available under the 
;I              terms and conditions of the BSD License which 
;I              accompanies this distribution. The full text of the 
;I              license may be found at 
;I              http://opensource.org/licenses/bsd-license.php
;I              
;I              THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "
;I              AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS OF 
;I              ANY KIND, EITHER EXPRESS OR IMPLIED.
;I
;I Description: Auto Created for EApi.inc
;I
;+------------------------------------------------------------------------=
;I
;I  File Name            : EApi.inc
;I  File Location        : include\masm
;I  Last committed       : $Revision$
;I  Last changed by      : $Author$
;I  Last changed date    : $Date$
;I  ID                   : $Id$
;I
;+=========================================================================
;</KHeader>
IFNDEF __COM0EEP_INC__
__COM0EEP_INC__ TEXTEQU <>

        include <COM0EEPConv.inc>

ENDIF  __COM0EEP_INC__
